version: '3'
services:
  db:
    environment:
      - DATABASE_PASSWORD=database_password
    image: nouchka/sqlite3:latest
    volumes:
      - ./db/:/root/db/
  app:
    # allow to debug inside image
    stdin_open: true
    tty: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
    ports:
      # "host:guest"
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      - LOCALHOST=http://localhost:3000
      - DATABASE_PASSWORD=database_password
